config/routes.rb
Rails.application.routes.draw do

  get 'test/index'
  get     '/admin',           to: 'admin#index'

  get     '/behaviors',       to: 'behaviors#index'
  get     '/welcome',         to: 'welcome#index'
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  delete  '/logout',          to: 'sessions#destroy'
  post    '/signup',          to: 'staffs#create'
  post    '/staffs/update',   to: 'staffs#update'
  post    '/students/create', to: 'students#create'
  post    '/students/update', to: 'sutdents#update'


  resources :parents
  resources :students
  resources :staffs
  resources :behaviors

  root 'welcome#index'
end

app/models/staff.rb
class Staff < ApplicationRecord

	before_save { email.downcase! }

  validates :fName,				presence: true, length: { maximum: 20 }
  validates :lName, 			presence: true, length: { maximum: 20 }
  validates :gradeTaught, presence: true

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

	def full_name_last
		"#{lName}, #{fName}"
	end
	def staff_member_info
		"#{lName}, #{fName} - Grade:#{gradeTaught}"
	end

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController

	def index
		@staffs = Staff.all
	end

	def show
		@staff = Staff.find(params[:id])
	end

	def new
		@staff = Staff.new
	end

	def edit
		@staff = Staff.find(params[:id])
	end

	def create
		@staff = Staff.new(staff_params)

		if @staff.save
			flash[:success] = "New Staff Member Added!"
			redirect_to admin_path
		else
			render 'new'
		end

		/@staff.save

		redirect_to @staff/
	end

	def update
		@staff = Staff.find(params[:id])
		if @staff.update(staff_params)
			flash[:success] = "Staff Member Updated!"
			redirect_to admin_path
		else
			render 'edit'
		end
	end

	def destroy
	  @staff = Staff.find(params[:id])
	  @staff.destroy
	  redirect_to staffs_path
	end

	private
	def staff_params
		params.require(:staff).permit(:fName, :lName, :gradeTaught, :email,
																:password, :password_confirmation)
	end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_error_messages.html.erb
<% if @staff.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@staff.errors.count, "error") %>.
    </div>
    <ul>
    <% @staff.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/staffs/_menu.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/admin">PBIS Monitor</a>
        </div>
        <ul class="nav navbar-nav navbar-right navbar-top-links">
        <li class="active"><a href="/admin"><i class="fa fa-star fa-fw"></i>Overview</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-edit fa-fw"></i> <i class="fa "></i>
                Behavior Event<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a href="<%= new_behavior_path %>"><i class="fa fa-plus-circle"></i> Add Event</a></li>
                <li><a href="/behaviors"><i class="fa fa-eye fa-fw"></i> View Events</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-users fa-fw"></i> <i class="fa "></i>
            Students<span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-user">
            <li><a href="<%= new_student_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Student</a>
            </li>
            <li><a href="/students"><i class="fa fa-search fa-fw"></i> View Students</a>
            </li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa "></i>
            Staff<span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-user">
            <li><a href="<%= new_staff_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Staff</a>
            </li>
            <li><a href="/staffs"><i class="fa fa-search fa-fw"></i> View Staff</a>
            </li>
            </ul>
            <!-- /.dropdown-user -->
            <li><%= link_to "Log out", logout_path, method: :delete %>
            </li>
        </li>
                    <!-- /.dropdown -->
          
        </ul>
      </div>
</nav>

app/views/staffs/edit.html.erb
<%= render 'menu' %>
<% provide(:title, 'Edit Staff Member') %>
<h1 align="center">Edit Staff Member</h1>

<%= render "layouts/header" %>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @staff, local: true do |f| %>

      <%= render 'error_messages' %>

      <%= f.label "First Name"  %>
      <%= f.text_field :fName, class: 'form-control' %>

      <%= f.label "Last Name" %>
      <%= f.text_field :lName, class: 'form-control' %>

      <%= f.label "Grade" %>
      <%= f.text_field :gradeTaught, class: 'form-control' %>

      <%= f.label "Email" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label "Password" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br/>

      <%= f.submit "Edit Staff Member", class: "btn btn-primary" %>
      <%= link_to 'Return to Main', admin_path, class: "btn btn-primary"  %>
    <% end %>
  </div>
</div>

app/views/staffs/index.html.erb
<%= render 'menu' %>
<h1>Current Staff Listing</h1>

<%= render "layouts/header" %>
<br/>


  <table class="table table-stripped">
    <tr>
      <th class="col-lg-1 col-sm-1"></th>
      <th class="col-lg-3 col-sm-3">First Name</th>
      <th class="col-lg-3 col-sm-3">Last Name</th>
      <th class="col-lg-1 col-sm-1">Show</th>
      <th class="col-lg-1 col-sm-1">Edit</th>
      <th class="col-lg-1 col-sm-1">Destroy</th>
      <th class="col-lg-2 col-sm-2"></th>
    </tr>
    <% @staffs.each do |staff| %>  
     <tr>
       <td></td>
      <td><%= staff.fName %></td>
      <td><%= staff.lName %></td>
      <td><%= link_to 'Show', staff_path(staff) %></td>
	  <td><%= link_to 'Edit', edit_staff_path(staff) %></td>
	  <td><%= link_to 'Destroy', staff_path(staff),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
       <td></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/staffs/new.html.erb
<%= render 'menu' %>
<% provide(:title, 'New Staff Member') %>
<h1 align="center">Add New Staff Member</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@staff, url: signup_path) do |f| %>
      <%= render 'error_messages' %>

      <%= f.label "First Name"  %>
      <%= f.text_field :fName, class: 'form-control' %>

      <%= f.label "Last Name" %>
      <%= f.text_field :lName, class: 'form-control' %>

      <%= f.label "Grade" %>
      <%= f.text_field :gradeTaught, class: 'form-control' %>

      <%= f.label "Email" %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label "Password" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>
      <br/>

      <%= f.submit "Add New Staff Member", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/staffs/show.html.erb
<%= render 'menu' %>
<h1>Staff</h1>

<%= render "layouts/header" %>

<div class = "container">
  <div class ="row">
    <div class = "col-sm">
    </div>
    <div class = "col-sm">

<p>
  <strong>First Name:</strong>
  <%= @staff.fName %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @staff.lName %>
</p>
<%= link_to 'Edit', edit_staff_path(@staff), class:"btn btn-primary" %> <br>
  <br>
<%= link_to 'Back', staffs_path, class:"btn btn-primary" %>

  		<div>
	<div>
<div>