config/routes.rb
Rails.application.routes.draw do

  get 'test/index'
  get     '/admin',           to: 'admin#index'

  get     '/behaviors',       to: 'behaviors#index'
  get     '/welcome',         to: 'welcome#index'
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  delete  '/logout',          to: 'sessions#destroy'
  post    '/signup',          to: 'staffs#create'
  post    '/staffs/update',   to: 'staffs#update'
  post    '/students/create', to: 'students#create'
  post    '/students/update', to: 'sutdents#update'


  resources :parents
  resources :students
  resources :staffs
  resources :behaviors

  root 'welcome#index'
end

app/models/student.rb
class Student < ApplicationRecord
	has_many :behavior

	validates :fName,				presence: true, length: { maximum: 20 }
  validates :lName, 			presence: true, length: { maximum: 20 }
  validates :grade, 			presence: true

	def full_name
		"#{fName} #{lName}"
	end

	def full_name_last
		"#{lName}, #{fName}"
	end
	
	def full_name_last_grade
		"#{lName}, #{fName} -#{grade}"
	end


end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

	def index
		@students = Student.all
	end

	def show
		@student = Student.find(params[:id])
	end

	def new
		@student = Student.new
	end

	def edit
		@student = Student.find(params[:id])
	end

	def create
		@student = Student.new(student_params)

		if @student.save
			flash[:success] = "New Student Added!"
			redirect_to admin_path
		else
			render 'new'
		end
		/@student.save
		redirect_to @student/
	end

	def update
		@student = Student.find(params[:id])
		if @student.update(student_params)
			flash[:success] = "Student Updated!"
			redirect_to admin_path
		else
			render 'edit'
		end
	end

	def destroy
	  @student = Student.find(params[:id])
	  @student.destroy
	  redirect_to students_path
	end

	private
	def student_params
		params.require(:student).permit(:fName, :lName, :grade, :homeroom_teacher)
	end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_error_messages.html.erb
<% if @student.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@student.errors.count, "error") %>.
    </div>
    <ul>
    <% @student.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/students/_menu.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/admin">PBIS Monitor</a>
        </div>
        <ul class="nav navbar-nav navbar-right navbar-top-links">
        <li class="active"><a href="/admin"><i class="fa fa-star fa-fw"></i>Overview</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-edit fa-fw"></i> <i class="fa "></i>
                Behavior Event<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a href="<%= new_behavior_path %>"><i class="fa fa-plus-circle"></i> Add Event</a></li>
                <li><a href="/behaviors"><i class="fa fa-eye fa-fw"></i> View Events</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-users fa-fw"></i> <i class="fa "></i>
            Students<span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-user">
            <li><a href="<%= new_student_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Student</a>
            </li>
            <li><a href="/students"><i class="fa fa-search fa-fw"></i> View Students</a>
            </li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa "></i>
            Staff<span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-user">
            <li><a href="<%= new_staff_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Staff</a>
            </li>
            <li><a href="/staffs"><i class="fa fa-search fa-fw"></i> View Staff</a>
            </li>
            </ul>
            <!-- /.dropdown-user -->
            <li><%= link_to "Log out", logout_path, method: :delete %>
            </li>
        </li>
                    <!-- /.dropdown -->
          
        </ul>
      </div>
</nav>

app/views/students/edit.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - PBIS</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <!-- Custom CSS -->
    <%= stylesheet_link_tag "sb-admin-2.css" %>
    <!-- Custom Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Datatables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
      $(document).ready( function () {
        $('#studentTable').DataTable();
        console.log("Document ready");
      } );
    </script>
</head>



<body>

    <div id="wrapper">

<% provide(:title, 'Edit Student') %>
<%= render 'menu' %>

<div id="" class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Edit Student</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="panel-body">

    <%= form_with model: @student, local: true do |f| %>

      <%= render 'error_messages' %>

      <%= f.label "First Name"  %>
      <%= f.text_field :fName, class: 'form-control' %>

      <%= f.label "Last Name" %>
      <%= f.text_field :lName, class: 'form-control' %>

      <%= f.label "Grade" %>
      <%= f.text_field :grade, class: 'form-control' %>

      <%= f.label "Teacher" %>
      <%= f.select :homeroom_teacher, Staff.all.collect { |s| [s.lName, s.id] }, {}, required: 'true', autofocus: 'false', class: 'form-control' %>

      <br/>

      <%= f.submit "Edit Student", class: "btn btn-primary" %>
      <%= link_to 'Back', students_path, class: "btn btn-primary" %>
      <% end %>
  </div>
		</div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <%= javascript_include_tag "jquery.min.js" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min.js" %>
    
</body>

app/views/students/index.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - PBIS</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <!-- Custom CSS -->
    <%= stylesheet_link_tag "sb-admin-2.css" %>
    <!-- Custom Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Datatables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
      $(document).ready( function () {
        $('#studentTable').DataTable();
        console.log("Document ready");
      } );
    </script>
</head>

<body>
    <div id="wrapper">
        <%= render 'menu' %>
        <div id="" class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Current Student List</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            
            <!-- NEED TO ADD NEW TABLE HERE -->
          <div >
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Student Table
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="studentTable">
                                <thead>
                                    <tr>
                                        <th>First Name</th>
                                        <th>Last Name</th>
                                        <th>Grade</th>
                                        <th>Homeroom Teacher</th>
                                        <th>View</th>
                                        <th>Edit</th>
                                        <th>Destroy</th>
                                    </tr>
                                </thead>
                                <tbody>
                                   <% @students.each do |student| %>
                                     <tr>
										<td><%= student.fName %></td>
										<td><%= student.lName %></td>
										<td><%= student.grade %></td>
										<td><%= student.homeroom_teacher %></td>
										<td><%= link_to 'Show', student_path(student) %></td>
										<td><%= link_to 'Edit', edit_student_path(student) %></td>
										<td><%= link_to 'Destroy', student_path(student),
													method: :delete,
													data: {confirm: 'Are you sure?'} %></td>
									</tr>
                                  <% end %>
                                </tbody>                               
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            
        </div>
        <!-- /#page-wrapper -->
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
        <%= link_to 'Back', students_path %>
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <%= javascript_include_tag "jquery.min.js" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min.js" %>
    
</body>

app/views/students/new.html.erb
<% provide(:title, 'New Student') %>

  <!-- Navigation -->
  <%= render 'menu' %>
  <h1 class="page-header" align="center">Add a New Student</h1>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_for(@student, url: students_create_path) do |f| %>
        <%= render 'error_messages' %>

        <%= f.label "First Name"  %>
        <%= f.text_field :fName, class: 'form-control' %>

        <%= f.label "Last Name" %>
        <%= f.text_field :lName, class: 'form-control' %>

        <%= f.label "Grade" %>
        <%= f.text_field :grade, class: 'form-control' %>

        <%= f.label "Teacher" %>
        <%= f.select :homeroom_teacher, Staff.all.collect { |s| [s.lName, s.id] }, {}, required: 'true', autofocus: 'false', class: 'form-control' %>

        <br/>

        <%= f.submit "Add New Student", class: "btn btn-primary" %>
        <%= link_to 'Back', students_path, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>

app/views/students/show.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - PBIS</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <!-- Custom CSS -->
    <%= stylesheet_link_tag "sb-admin-2.css" %>
    <!-- Custom Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Datatables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
      $(document).ready( function () {
        $('#studentTable').DataTable();
        console.log("Document ready");
      } );
    </script>
</head>

<body>

    <div id="wrapper">

        <%= render 'menu' %>

        <div id="" class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Student</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            <div class="panel-body">
            <p>
			 <strong>First Name:</strong>
			 <%= @student.fName %>
			<br>
				<strong>Last Name:</strong>
				<%= @student.lName %>
			<br>
				<strong>Grade:</strong>
				<%= @student.grade %>
	      <br>
			<strong>Homeroom Teacher:</strong>
			<%= @student.homeroom_teacher %>
		  </p><br>
		  <%= link_to 'Edit', edit_student_path(@student), class:"btn btn-primary" %>
            <!-- /.row -->
        </div>
		</div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <%= javascript_include_tag "jquery.min.js" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min.js" %>
    
</body>