config/routes.rb
Rails.application.routes.draw do

  get 'test/index'
  get     '/admin',           to: 'admin#index'

  get     '/behaviors',       to: 'behaviors#index'
  get     '/welcome',         to: 'welcome#index'
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  delete  '/logout',          to: 'sessions#destroy'
  post    '/signup',          to: 'staffs#create'
  post    '/staffs/update',   to: 'staffs#update'
  post    '/students/create', to: 'students#create'
  post    '/students/update', to: 'sutdents#update'


  resources :parents
  resources :students
  resources :staffs
  resources :behaviors

  root 'welcome#index'
end

app/views/admin/_menu.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/admin">PBIS Monitor</a>
        </div>
        <ul class="nav navbar-nav navbar-right navbar-top-links">
        <li class="active"><a href="/admin"><i class="fa fa-star fa-fw"></i>Overview</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-edit fa-fw"></i> <i class="fa "></i>
                Behavior Event<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a href="<%= new_behavior_path %>"><i class="fa fa-plus-circle"></i> Add Event</a></li>
                <li><a href="/behaviors"><i class="fa fa-eye fa-fw"></i> View Events</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-users fa-fw"></i> <i class="fa "></i>
            Students<span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-user">
            <li><a href="<%= new_student_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Student</a>
            </li>
            <li><a href="/students"><i class="fa fa-search fa-fw"></i> View Students</a>
            </li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa "></i>
            Staff<span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-user">
            <li><a href="<%= new_staff_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Staff</a>
            </li>
            <li><a href="/staffs"><i class="fa fa-search fa-fw"></i> View Staff</a>
            </li>
            </ul>
            <!-- /.dropdown-user -->
            <li><%= link_to "Log out", logout_path, method: :delete %>
            </li>
        </li>
                    <!-- /.dropdown -->
          
        </ul>
      </div>
</nav>

app/views/admin/index.html (copy).erb
<h1>Admin#index</h1>
<p>Find me in app/views/admin/index.html.erb</p>
<p> but why??</p>

app/views/admin/index.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - PBIS</title>

</head>

<body>
    <%= content_tag :div, "", id: "week_events", data:{behaviors: @weekData}%>
     <%= content_tag :div, "", id: "month_events", data:{behaviors: @monthData}%>
    <div id="wrapper">

        <!-- Navigation -->
        <%= render 'menu' %>

        <div id="" class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Dashboard</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div> 
            <!-- /.row -->
            
            <div class="row">
                <div class="col-lg-8">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Events This Week
                        </div>
                       
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                           
                           
                            <div id="eventByWeek" style="height: 250px;"></div>

                        </div>
                        <!-- /.panel-body -->
                    </div>                    
                </div>
                <div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Recent Events
                        </div>
                        <!-- /.panel-heading -->
                        <table width="100%" class="table table-striped table-bordered table-hover table-condensed" id="recentEvents">
                                <thead>
                                    <tr>
                                        <th>Student</th>
                                        <th>Date</th>
                                        <th>Time</th>
                                        <th>View</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <% @recentEvents.each do |behave| %> 
                                    <tr>
                                      <td><%= behave.student_name%></td>
                                      <td><%= behave.event_date %></td>
                                      <td><%= behave.readable_time %></td>
                                      <td><%= link_to 'Show', behavior_path(behave) %></td>
                                    </tr>
                                  <% end %>
                                </tbody>                               
                            </table>
                            <!-- /.table-responsive -->
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-8">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bar-chart-o fa-fw"></i> Events By Month
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div id="eventByMonth" style="height: 250px;"></div>
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-8 -->
                <div class="col-lg-4">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            <i class="fa fa-bell fa-fw"></i> Frequent Behaviors
                            <table width="100%" class="table table-striped table-bordered table-hover table-condensed" id="recentEvents">
                                <thead>
                                    <tr>
                                       <th># Events</th>
                                       <th>Name</th>
                                       <th>View</th>
                                    </tr>
                                </thead>

                                <tbody>
                                    
                                    <% @highFliers.each do |s| %> 
                                    <tr>
                                      <td><%= s.count %></td>
                                      <td><%= s.student_name %></td>
                                      <td><%= link_to 'View', student_path(s.student_id) %></td>
                                    </tr>
                                  <% end %>
                                </tbody>                               
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-heading -->
                        
                    </div>
                </div>

            </div>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

    </div>
    
    <!-- /#wrapper -->

    <!-- Charts -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>

    <script type="text/javascript">
        new Morris.Bar({
            element: 'eventByMonth',
            data: $('#month_events').data('behaviors'),
            xkey: 'event_date',
            ykeys: ['count'],
            labels: ['Events'],
            resize: true
        });
        new Morris.Bar({
            element: 'eventByWeek',
            data: $('#week_events').data('behaviors'),
            xkey: 'event_date',
            ykeys: ['count'],
            labels: ['Events'],
            resize: true
        });
        
        
    </script>
    

</body>