config/routes.rb
Rails.application.routes.draw do

  get 'test/index'
  get     '/admin',           to: 'admin#index'

  get     '/behaviors',       to: 'behaviors#index'
  get     '/welcome',         to: 'welcome#index'
  get     '/login',           to: 'sessions#new'
  post    '/login',           to: 'sessions#create'
  delete  '/logout',          to: 'sessions#destroy'
  post    '/signup',          to: 'staffs#create'
  post    '/staffs/update',   to: 'staffs#update'
  post    '/students/create', to: 'students#create'
  post    '/students/update', to: 'sutdents#update'


  resources :parents
  resources :students
  resources :staffs
  resources :behaviors

  root 'welcome#index'
end

app/models/behavior.rb
class Behavior < ApplicationRecord
	has_one :student
	
	def readable_time
		event_time.strftime("%I:%M%p")  
	end

	def student_name
		# check if there is a student id
		if student_id
			# is it valid?
			begin
				Student.find(student_id).full_name_last
			rescue Exception => e
				"unknown"
			end
			
		else
			"unknown"
		end

	end

	def staff_name
		# check if there is a student id
		if staff_id
			Staff.find(staff_id).full_name_last
		else
			"unknown"
		end

	end

	


end

app/controllers/behaviors_controller.rb
class BehaviorsController < ApplicationController
  def index
		@behavior = Behavior.all
	end
  
	def show
		@behavior = Behavior.find(params[:id])
	end
	
	def new
		@behavior = Behavior.new
	end
	
	def edit
		@behavior = Behavior.find(params[:id])
	end
	
	def create
		@behavior = Behavior.new(behavior_params)
		
		if @behavior.save
			redirect_to @behavior
		else
			render 'new'
		end
		
		/@behavior.save

		redirect_to @behavior/
	end
	
	def update
		@behavior = Behavior.find(params[:id])
		if @behavior.update(behavior_params)
			redirect_to @behavior
		else
			render 'edit'
		end
	end
	
	def destroy
	  @behavior = Behavior.find(params[:id])
	  @behavior.destroy
	  redirect_to behaviors_path
	end
	
	private
	def behavior_params 
		params.require(:behavior)
		.permit(:student_id, :event_date, :event_time, :locaton, :peers_involved, :staff_id, :get_peer_attention, :get_adult_attention, :get_items_activities, :avoid_task, :avoid_peer, :avoid_adult,:motivation,:minor_language,:minor_contact,:minor_defiance, :minor_disruption,:minor_property,:minor_dress,:minor_technology,:minor_tardy, :minor_other,:major_language,:major_aggression,:major_disrespect,:major_habitual_disruption,:major_dishonesty, :major_harrassment,:major_tardies,:major_vandalism,:major_theft,:major_dress_code, :major_drugs,:major_weapons,:major_other,:antecedent,:behavior_description,:due_process,:admin_time_office,:admin_loss_privilege,:admin_conference_student,:admin_parent_contact,:admin_detention,:admin_service,:admin_individual_instruction,:admin_counselor,:admin_in_school_suspension,:admin_suspension,:admin_expulsion,:admin_other)
		end
end

app/helpers/behavior_helper.rb
module BehaviorHelper
end

app/views/behaviors/_menu.html (copy).erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                
                <a class="navbar-brand" href="/welcome/index">PBIS Monitor</a>
            </div>
            <!-- /.navbar-header -->

           

            <ul class="nav navbar-top-links navbar-right">
                <li><a href="/admin/index"><i class="fa fa-star fa-fw"></i> Overview</a>
                    </li>
                 <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <i class="fa fa-edit fa-fw"></i> <i class="fa "></i>
                      Behavior Event
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="<%= new_behavior_path %>"><i class="fa fa-plus-circle"></i> Add Event</a>
                            
                        </li>
                        <li><a href="/behaviors"><i class="fa fa-eye fa-fw"></i> View Events</a>                       
                    </ul>
                    <!-- /.dropdown-user -->
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <i class="fa fa-users fa-fw"></i> <i class="fa "></i>
                      Students
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="<%= new_student_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Student</a>
                        </li>
                        <li><a href="/students"><i class="fa fa-search fa-fw"></i> View Students</a>
                        </li>
                    </ul>
                </li>
                <!-- /.dropdown -->
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                      <i class="fa fa-user fa-fw"></i> <i class="fa "></i>
                      Staff
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="<%= new_staff_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Staff</a>
                        </li>
                        <li><a href="/staffs"><i class="fa fa-search fa-fw"></i> View Staff</a>
                        </li>
                    </ul>
                    <!-- /.dropdown-user -->
                    <li><a href="/login/index"><i class="fa fa-sign-out fa-fw"></i> Logout</a>
                    </li>
                </li>
                <!-- /.dropdown -->
                
            </ul>
            <!-- /.navbar-top-links -->

            
            <!-- /.navbar-static-side -->
        </nav>

app/views/behaviors/_menu.html.erb
<!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top">
        <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="/admin">PBIS Monitor</a>
        </div>
        <ul class="nav navbar-nav navbar-right navbar-top-links">
        <li class="active"><a href="/admin"><i class="fa fa-star fa-fw"></i>Overview</a></li>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                <i class="fa fa-edit fa-fw"></i> <i class="fa "></i>
                Behavior Event<span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
                <li><a href="<%= new_behavior_path %>"><i class="fa fa-plus-circle"></i> Add Event</a></li>
                <li><a href="/behaviors"><i class="fa fa-eye fa-fw"></i> View Events</a></li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-users fa-fw"></i> <i class="fa "></i>
            Students<span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-user">
            <li><a href="<%= new_student_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Student</a>
            </li>
            <li><a href="/students"><i class="fa fa-search fa-fw"></i> View Students</a>
            </li>
            </ul>
        </li>
        <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
            <i class="fa fa-user fa-fw"></i> <i class="fa "></i>
            Staff<span class="caret"></span>
            </a>
            <ul class="dropdown-menu dropdown-user">
            <li><a href="<%= new_staff_path %>"><i class="fa fa-plus-circle fa-fw"></i> Add Staff</a>
            </li>
            <li><a href="/staffs"><i class="fa fa-search fa-fw"></i> View Staff</a>
            </li>
            </ul>
            <!-- /.dropdown-user -->
            <li><%= link_to "Log out", logout_path, method: :delete %>
            </li>
        </li>
                    <!-- /.dropdown -->
          
        </ul>
      </div>
</nav>

app/views/behaviors/edit.html.erb
<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - PBIS</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- MetisMenu CSS -->
    <link rel="stylesheet" href="https://unpkg.com/metismenu/dist/metisMenu.min.css">
    <!-- Custom CSS -->
    <%= stylesheet_link_tag "sb-admin-2.css" %>
    <!-- Custom Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <%= render 'menu' %>

        <div id="" class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Edit Event</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            
            <%= render 'form' %>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->

        <%= link_to 'Back', behavior_path %>
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <%= javascript_include_tag "jquery.min.js" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min.js" %>
    
</body>

app/views/behaviors/index.html (copy).erb
<h1>Listing Behaviors</h1>
 <br/>
 
<table>
  <tr>
    <th>Student</th>
    <th>Date</th>
    <th>Time</th>
    <th>Description</th>
    <th>View</th>
  </tr>

  <% @behavior.each do |behave| %>
    
    <tr>
      <td><%= behave.student_name%></td>
      <td><%= behave.event_date %></td>
      <td><%= behave.readable_time %></td>
      <td><%= behave.behavior_description %></td>
      <td><%= link_to 'Show', behavior_path(behave) %></td>
    </tr>
  <% end %>

</table>
<br>
<%= link_to 'Home', controller: 'welcome' %>

app/views/behaviors/index.html.erb
 


<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - PBIS</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    
    <!-- Custom CSS -->
    <%= stylesheet_link_tag "sb-admin-2.css" %>
    <!-- Custom Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <!-- Datatables CSS -->
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css">
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script>
      $(document).ready( function () {
        $('#studentTable').DataTable();
        console.log("Document ready");
      } );
    </script>
</head>

<body>

    <div id="wrapper">
        <%= render 'menu' %>
        

        <div id="" class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Listing Behavior Events</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            
            <!-- NEED TO ADD NEW TABLE HERE -->
          <div >
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">
                            Student Behavior Table
                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <table width="100%" class="table table-striped table-bordered table-hover" id="studentTable">
                                <thead>
                                    <tr>
                                        <th>Student</th>
                                        <th>Date</th>
                                        <th>Time</th>
                                        <th>Description</th>
                                        <th>View</th>
                                        <th>Edit</th>
                                        <th>Destroy</th>
                                    </tr>
                                </thead>
                                <tbody>
                                  <% @behavior.each do |behave| %>
                                    <tr>
                                      <td><%= behave.student_name%></td>
                                      <td><%= behave.event_date %></td>
                                      <td><%= behave.readable_time %></td>
                                      <td><%= behave.behavior_description %></td>
                                      <td><a href="/behaviors/<%= behave.id %>">View</a></td>
                                      <td><%= link_to 'Edit', edit_behavior_path(behave) %></td>
                                      <td><%= link_to 'Destroy', behavior_path(behave),
                                                    method: :delete,
                                                    data: {confirm: 'Are you sure?'} %></td>
                                    </tr>
                                  <% end %>
                                </tbody>                               
                            </table>
                            <!-- /.table-responsive -->
                        </div>
                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            
        </div>
        <!-- /#page-wrapper -->
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
        <%= link_to 'Home', controller: 'welcome' %>
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <%= javascript_include_tag "jquery.min.js" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min.js" %>
    
</body>

app/views/behaviors/new.html.erb
 


<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Admin - PBIS</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- MetisMenu CSS -->
    <link rel="stylesheet" href="https://unpkg.com/metismenu/dist/metisMenu.min.css">
    <!-- Custom CSS -->
    <%= stylesheet_link_tag "sb-admin-2.css" %>
    <!-- Custom Fonts -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
       <%= render 'menu' %>

        <div id="" class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">Record Behavior Event</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
            
            <%= render 'form' %>
            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->
        <%= link_to 'Back', behaviors_path %>
    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <%= javascript_include_tag "jquery.min.js" %>

    <!-- Bootstrap Core JavaScript -->
    <%= javascript_include_tag "bootstrap.min.js" %>
    
</body>